/'
Er der links heri som ikke længere er aktuelle eller fejl, så giv mig venligst besked. 
lbha@ucl.dk / Systemdevelopmentguy@gmail.com

Dette er en skabelon til et Aktivitets diagram (Activity Diagram). I forbindelse med at I skal lære om BPMN, 
så starter vi med at lave aktivitetsdiagrammer.

Aktivitets diagrammer er mere enkle fremfor BPMN, og derfor er Aktivitets diagrammer også virkelig gode til
beskrive eksisterende og kommende flows sammen med kunden - som ikke bliver så mentalt overvældet. 
Tænk på at kunden ofte bliver præsenteret for dokumenterne, som bliver fremstillet i analyserne. Så lige så 
svært, som det er for jer. Lige så svært kan det være for en kunde, som ikke har jeres indsigt i artefakterne.
Faktisk kan det være sværere for kunden, da de sjældent har tiden - som I har - til at lære og sætte sig ind i 
artefakterne.

Derfor er Aktivitets diagrammet virkelig godt, at starte med. Hvis kunden - typisk større, mere etablerede og 
professionelle virksomheder (ingeiørfirmaer, banker, forsikringsselskaber, medicinproducenter, dele af det 
offentlige, m.fl.) - har viden og resourcer til at kende og anvende BPMN, så skifter vi gerne til det på kundens 
opfordring. Der findes altid undtagelser, men de fleste mindre virksomheder foretrækker Aktivitets diagrammer.

Da vi som nævnt ikke har helt så mange udtryksformer i Aktivitets diagrammerne som i BPMN. F.eks. er der i 
Aktivitets diagrammer intet Message element. Så udtrykker vi det selv eksplicit i teksten
"Message | Giv totalpris". Se i eksemplet herunder.

Husk at vi i analysefasen gør alt hvad vi kan for at holde sprogvalget til det som vores kunde (Product Owner) 
bruger i det daglig i deres forretning. Så undgå sprogblanding med dansk og engelsk. (danglish)


I denne fil anvender vi PlantUML (Activity Diagram) til at tegne tegne aktiviteterne i virksomheden.
Du finder en masse eksempler her: 
https://plantuml.com/activity-diagram-beta

Der er elementer i BPMN, som ikke findes i aktivitet Diagram, som beskrevet ovenfor. Så løser vi det ved selv
at beskrive elementet: Eks. "Message | Giv totalpris". Nu er det skrevet to gange, så bid mærke i det :-).

Kodeeksempel på Celine's Cykellapning: 

@startuml
title Celine's Cykellapning
|Kunde|
start
:Aflevere punkteret cykel;
|Celine|
:Modtage punkteret cykel;
if (Undersøg cykelslange) is (Lappes) then
:Lappes | find pris lapning;
else (Ny slange)
|Celine|
:Slange | find pris slange;
endif 
if (Undersøg cykeldæk) is (Dæk ok) then
else (Nyt dæk)
:Dæk | find pris nyt dæk;
endif 
|Kunde|
-[dashed]->
:Message | Giv totalpris;
stop

@enduml

Når I retter i jeres kode kan I få Visual Studio Code til at gentegne (preview) ved at taste [Alt]+[d].


@startuml
/' 
Da vi ønsker at gemme vores arbejde i git, så vil vi gerne udnytte at git er linjebaseret. 
Det giver STORE fordele for jer senere.

SÅ HUSK AT SKRIVE TINGENE SEPARAT PÅ HVER SIN LINJE. 
F.eks. 
LAV LINJESKIFT NÅR I HAR TILFØJET: ":Aflevere punkteret cykel;"
OG IGEN LAV LINJESKIFT NÅR I HAR TILFØJET: "|Celine|"
'/

title Celine's Cykellapning
|Kunde|
start
:Aflevere punkteret cykel;
|Celine|
:Modtage punkteret cykel;
if (Undersøg cykelslange) is (Lappes) then
:Lappes | find pris lapning;
else (Ny slange)
|Celine|
:Slange | find pris slange;
endif 
if (Undersøg cykeldæk) is (Dæk ok) then
else (Nyt dæk)
:Dæk | find pris nyt dæk;
endif 
|Kunde|
-[dashed]->
:Message | Giv totalpris;
stop

@enduml